sudo: required

os:
  - osx
  - linux

language: node_js
node_js:
- 10.15.2

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

install:
  - yarn
  - yarn upgrade caniuse-lite browserslist

script:
  - yarn lint || travis_terminate 1
  - yarn test || travis_terminate 1
  - yarn build || travis_terminate 1
  - yarn i18n-check-dupes || travis_terminate 1
